// Booking IDs use AR + year + month (India time) + a 4-digit suffix, e.g.
// AR2026091842. They are generated by the database (public.create_booking).
export const BOOKING_ID_PATTERN = /^AR\d{10}$/;

export function normalizeBookingId(value: string) {
  return value.replace(/\s/g, "").toUpperCase();
}
